name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: 'pnpm'

      # Install dependencies first so that esbuild (and other packages) are available
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build plugin for release
        env:
          NODE_ENV: production
        run: pnpm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_name="${GITHUB_REF#refs/tags/}"
          echo "Creating release for tag: $tag_name"

          # Create an array of assets to upload
          assets_to_upload=()
          if [ -f "main.js" ]; then assets_to_upload+=("main.js"); else echo "WARNING: main.js not found!"; fi
          if [ -f "manifest.json" ]; then assets_to_upload+=("manifest.json"); else echo "WARNING: manifest.json not found!"; fi
          if [ -f "styles.css" ]; then assets_to_upload+=("styles.css"); else echo "WARNING: styles.css not found (optional)!"; fi

          if [ ${#assets_to_upload[@]} -eq 0 ]; then
            echo "ERROR: No assets found to upload. Aborting release."
            exit 1
          fi

          echo "Uploading assets: ${assets_to_upload[*]}"

          gh release create "$tag_name" \
            --title "$tag_name" \
            --notes "Release for version $tag_name" \
            --generate-notes \
            "${assets_to_upload[@]}"
